<?php

namespace AppBundle\Repository;

/**
 * AdvertLangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertLangRepository extends \Doctrine\ORM\EntityRepository
{
}
