<?php

namespace AppBundle\Repository;

/**
 * AuctionBidRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuctionBidRepository extends \Doctrine\ORM\EntityRepository
{
}
