<?php

namespace AppBundle\Repository;

/**
 * FineartsAuctionObserveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuctionWorkObserveRepository extends \Doctrine\ORM\EntityRepository
{
}
