<?php

namespace AppBundle\Repository;

/**
 * AuctionWorkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuctionWorkRepository extends \Doctrine\ORM\EntityRepository
{
}
