<?php

namespace AppBundle\Repository;

/**
 * ExhibitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExhibitionRepository extends \Doctrine\ORM\EntityRepository
{
}
