<?php

namespace AppBundle\Repository;

/**
 * HouseAuctionObserveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HouseAuctionObserveRepository extends \Doctrine\ORM\EntityRepository
{
}
