<?php

namespace AppBundle\Repository;

/**
 * HouseAuctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HouseAuctionRepository extends \Doctrine\ORM\EntityRepository
{
}
