<?php

namespace AppBundle\Repository;

/**
 * HouseAuctionWorkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HouseAuctionWorkRepository extends \Doctrine\ORM\EntityRepository
{
}
