<?php

namespace AppBundle\Repository;

/**
 * StaticPageLangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaticPageLangRepository extends \Doctrine\ORM\EntityRepository
{
}
