<?php

namespace AppBundle\Repository;

/**
 * UserLookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserLookingRepository extends \Doctrine\ORM\EntityRepository
{
}
