<?php

namespace AppBundle\Repository;

/**
 * WorkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkRepository extends \Doctrine\ORM\EntityRepository
{
    public function checkSlug( $slug, $id = 0){

        /** @var QueryBuilder $query */
        $query = $this->createQueryBuilder('u')
            ->select('count( u.id )')
            ->where('u.slug Like :new_slug' )
            ->andWhere('u.id <> :new_id' );
        $query->setParameter('new_id', $id);
        $is_url = true;
        do {
            $query->setParameter('new_slug', $slug);
            $urls_count = $query->getQuery()->getSingleResult();
            if( !isset( $urls_count[1] )
                || ( (int)$urls_count[1] == 0 )
            ) {
                $is_url = false;
                break;
            }
            else
            {
                $slug .= '-'.$urls_count[1];
            }
        } while( $is_url );
        return $slug;
    }
    public function update($work)
    {
        try {
            $this->_em->persist($work);
            $this->_em->flush();
        } catch(\Exception $e)
        {
            return false;
        }
        return true;
    }
}
