<?php

namespace AppBundle\Repository;

/**
 * WorkConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkConfigRepository extends \Doctrine\ORM\EntityRepository
{
}
