_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /
kcfinder:
    resource: "@KCFinderBundle/Resources/config/routing.yml"
    prefix: /admin
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
#_errors:
#    resource: "@TwigBundle/Resources/config/routing/errors.xml"
#    prefix:   /_error
