<?php

namespace AdminBundle\Repository;

/**
 * NewsletterTestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterTestRepository extends \Doctrine\ORM\EntityRepository
{
}
