<?php

namespace UserBundle\Repository;

/**
 * UserVisitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserVisitsRepository extends \Doctrine\ORM\EntityRepository
{
}
